<?php

/**
 * @file
 * Contains as_candidature.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_candidature_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_candidature module.
    case 'help.page.as_candidature':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides job for people') . '</p>';
      return $output;

    default:
  }
}
